### ISSUE TITLE
Does simurg result obtain paralogs?

### ISSUE THREAD

**Issue by bucongfan** [iferres/simurg#11]
Hi, iferres

Thank you for this software!

I am using simurg to test my pangenome software,

I wonder if can simurg result have paralogs, cause I found all gene ID forms as genomeX_geneX.

It seems like each cluster is an orthologs, although it may come from the same reference gene,  is that right?

Thank you!

**Comment by iferres** [comment]
Hi @bucongfan , the `replace = TRUE` parameter allows resampling the same reference gene in different timepoints of the simulation. If `replace = FALSE` (default), then you must provide enough reference genes to avoid running out of them, and the simulation will stop with an error if it run out.

**Comment by bucongfan** [comment]
Ok, thank you for your help!
